import { GoogleGenAI } from "@google/genai";
import { FlowStore } from "./flow-store";
import { detectExternalDeps } from "./dep-detector";
import { loadConfig } from "../config";
import { getEffectiveSettings } from "../ai/mode-presets";
import type { InterviewQuestion, FlowDocument } from "../types";

function prependHeader(
  format: string,
  flowName: string,
  trigger: string,
  content: string,
  usageMarkdown: string
): string {
  const now = new Date().toISOString();
  switch (format) {
    case "python": {
      // Strip an existing model-written docstring and replace with ours so the
      // usage block is always present and consistent.
      const stripped = content.replace(/^(?:"""[\s\S]*?"""|'''[\s\S]*?''')\s*/m, "");
      const usageAsComment = usageMarkdown
        .split("\n")
        .map((l) => (l ? `# ${l}` : "#"))
        .join("\n");
      return `"""\n${flowName}\n\nGenerated by FlowMind on ${now}.\nTrigger: ${trigger}\n"""\n\n${usageAsComment}\n\n${stripped}`;
    }
    case "nodejs": {
      const stripped = content.replace(/^\/\*[\s\S]*?\*\/\s*/m, "");
      const usageAsComment = usageMarkdown
        .split("\n")
        .map((l) => (l ? ` * ${l}` : " *"))
        .join("\n");
      return `/**\n * ${flowName}\n *\n * Generated by FlowMind on ${now}.\n * Trigger: ${trigger}\n *\n${usageAsComment}\n */\n\n${stripped}`;
    }
    case "claude-skill": {
      // Claude skill files must stay clean — only frontmatter and body.
      // If the model didn't write frontmatter, add a minimal one; otherwise trust it.
      if (content.startsWith("---")) return content;
      const skillName = flowName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
      return `---\nname: ${skillName}\ndescription: ${trigger || flowName}\n---\n\n${content}`;
    }
    case "tutorial": {
      return `# ${flowName} — Tutorial\n\n> This document is a step-by-step tutorial generated by FlowMind from an observed workflow. It describes how to perform the task manually. No installation or tools required — just follow the steps in order.\n>\n> Generated: ${now}\n\n## How to use this file\n\n${usageMarkdown}\n\n---\n\n${content}`;
    }
    default:
      return content;
  }
}

function buildUsageInstructions(format: string, filePath: string, content: string): string {
  switch (format) {
    case "python": {
      const external = detectExternalDeps(content, "python");
      const lines = [
        `**How to run this script**`,
        "",
        "```bash",
        `python "${filePath}"`,
        "```",
      ];
      if (external.length > 0) {
        lines.push("", `This script imports non-stdlib packages. Install them first:`, "", "```bash", `pip install ${external.join(" ")}`, "```");
      }
      return lines.join("\n");
    }
    case "nodejs": {
      const external = detectExternalDeps(content, "nodejs");
      const lines = [
        `**How to run this script**`,
        "",
        "```bash",
        `node "${filePath}"`,
        "```",
      ];
      if (external.length > 0) {
        lines.push("", `This script imports non-builtin packages. Install them first:`, "", "```bash", `npm install ${external.join(" ")}`, "```");
      }
      return lines.join("\n");
    }
    case "claude-skill": {
      return [
        `**How to use this as a Claude Code skill**`,
        "",
        `1. Copy this file into the \`.claude/skills/\` folder of any project where you want to use it`,
        `2. The skill will be auto-discovered by Claude Code next time you open that project`,
        `3. Invoke it by typing \`/<skill-name>\` in the Claude Code chat`,
      ].join("\n");
    }
    case "tutorial": {
      return [
        `**How to use this tutorial**`,
        "",
        `This is a plain markdown document. Open it in any markdown viewer or text editor and follow the steps in order. Nothing to install, nothing to run.`,
      ].join("\n");
    }
    default:
      return "";
  }
}

const AUTOMATION_PROMPT = `You are FlowMind, an AI that generates automations from documented workflows.

Given the complete flow document below, generate the requested output format.

PRIMARY RULE — AUTOMATE THE GOAL, NOT THE KEYSTROKES.

The observed steps describe HOW the user did something manually (open browser, click link, Ctrl+S, type filename, press Enter). Your job is to achieve the SAME RESULT using the lightest possible code — not to replay those exact clicks.

Examples:
- Observed: "user typed google.com, searched, clicked an article, Ctrl+S, typed filename, saved to Documents."
  Wrong: selenium drives a browser, clicks search, pyautogui types into the Save-As dialog.
  Right: urllib.request fetches the article URL, writes bytes to the target file. No browser, no clicks.
- Observed: "user opened calendar.google.com, clicked New Event, filled title, saved."
  Wrong: selenium clicks through the Google Calendar UI.
  Right: Google Calendar API call, authenticated from env vars.
- Observed: "user right-clicked a file and used Move to..."
  Wrong: pyautogui navigates the context menu.
  Right: shutil.move() or pathlib.Path.rename().

DEPENDENCY ORDER — use the LIGHTEST tool that solves the goal:
1. Standard library ALWAYS first (pathlib, shutil, urllib.request, smtplib, subprocess, json, re, datetime, os, csv, sqlite3).
2. A widely-available single-purpose library next (requests for HTTP if cleaner than urllib; a specific API SDK like google-api-python-client for a Google service).
3. UI automation (playwright, selenium, pyautogui, pyperclip, webdriver-manager) is a LAST RESORT. Only use it when the goal TRULY cannot be done via API, CLI, or filesystem:
   - A desktop app with no exposed API (Photoshop filter, Figma canvas manipulation via UI)
   - A web app that requires CAPTCHA-like human interaction
   - A GUI-only installer or legacy Windows tool
   When you DO reach for browser automation, prefer Playwright over Selenium — it's faster, bundles its own browser via \`playwright install\`, and is much less flaky. Use Selenium only when Playwright genuinely can't do the job.
   Any time you use UI automation, state clearly in the opening docstring WHY no lighter option exists.

OTHER RULES:
- The automation must achieve the flow's outcome. ALL steps' collective goal must be reached — but individual steps may be collapsed or replaced with a lighter equivalent.
- Include error handling for network calls and filesystem operations.
- Add comments explaining any non-obvious decision logic.
- Never hardcode sensitive values — read from environment variables or prompt the user at first run.
- Mark steps that need human approval with clear interactive prompts (e.g. input() in Python).

Respond with ONLY the requested code/document, no explanations.`;

export class InterviewEngine {
  private store: FlowStore;
  private genai: GoogleGenAI;

  constructor(store: FlowStore) {
    this.store = store;

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    this.genai = new GoogleGenAI({ apiKey });
  }

  private async getAutomationModel(): Promise<string> {
    const config = await loadConfig();
    return getEffectiveSettings(config).automationModel;
  }

  async getQuestions(flowId: string): Promise<InterviewQuestion[]> {
    const flow = await this.store.getFlowById(flowId);
    if (!flow) throw new Error(`Flow not found: ${flowId}`);
    if (flow.frontmatter.type !== "partial-flow") {
      return []; // complete flows have no questions
    }

    const questions: InterviewQuestion[] = [];
    const lines = flow.body.split("\n");
    let inQuestions = false;
    let index = 0;

    for (const line of lines) {
      if (line.includes("## Questions to Complete This Flow")) {
        inQuestions = true;
        continue;
      }
      if (inQuestions && line.startsWith("##")) break;
      if (inQuestions && line.startsWith("- Q")) {
        const questionText = line.replace(/^- Q\d+:\s*/, "").trim();
        questions.push({
          index,
          question: questionText,
          answered: false,
        });
        index++;
      }
    }

    return questions;
  }

  async submitAllAnswers(
    flowId: string,
    answers: Record<number, string>
  ): Promise<{ promoted: boolean; newQuestions?: InterviewQuestion[] }> {
    const flow = await this.store.getFlowById(flowId);
    if (!flow) throw new Error(`Flow not found: ${flowId}`);

    const questions = await this.getQuestions(flowId);

    // Insert all answers into the body
    let updatedBody = flow.body;
    for (const q of questions) {
      const answer = answers[q.index];
      if (answer?.trim()) {
        q.answered = true;
        q.answer = answer;
        updatedBody = this.insertAnswer(
          { ...flow, body: updatedBody },
          q.index,
          answer
        );
      }
    }

    // Ask Gemini to evaluate: promote to complete, or generate follow-up questions
    const evalResult = await this.evaluateCompleteness(flow, updatedBody);

    if (evalResult.status === "complete") {
      await this.promoteToComplete(
        { ...flow, body: updatedBody },
        evalResult.body
      );
      return { promoted: true };
    }

    // Still gaps — update the partial flow with answers + new questions
    const newBody = this.replaceQuestions(updatedBody, evalResult.questions);
    const newFrontmatter = {
      ...flow.frontmatter,
      gaps: evalResult.questions.length,
    };
    await this.store.updateFlow(flow.filePath, newFrontmatter, newBody);

    const newQuestions = evalResult.questions.map((q, i) => ({
      index: i,
      question: q,
      answered: false,
    }));

    return { promoted: false, newQuestions };
  }

  private async evaluateCompleteness(
    flow: FlowDocument,
    bodyWithAnswers: string
  ): Promise<
    | { status: "complete"; body: string }
    | { status: "incomplete"; questions: string[] }
  > {
    const response = await this.genai.models.generateContent({
      model: await this.getAutomationModel(),
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `You are FlowMind. A user answered interview questions about a partial workflow. Evaluate whether the flow is now complete enough to document, or if there are still gaps.

Respond with ONLY valid JSON in one of these formats:

If the flow is complete (all steps are clear and reproducible):
{
  "status": "complete",
  "body": "Full markdown flow document (# Name, ## Trigger, ## Steps, ## Decision Logic, ## Tools & Data Sources, ## Automation Classification, ## Variations Observed)"
}

If there are still gaps that need clarification:
{
  "status": "incomplete",
  "questions": ["Q1: specific follow-up question", "Q2: ..."]
}

Rules:
- A flow is complete when ALL steps are clear, specific, and reproducible by someone else
- If the user's answers introduced new ambiguity or referenced unknown steps, ask about those
- Keep follow-up questions specific and actionable
- Do NOT ask more than 3 follow-up questions at a time`,
            },
            {
              text: `\n\n## Partial Flow with Answers\n${bodyWithAnswers}`,
            },
          ],
        },
      ],
      config: { responseMimeType: "application/json" },
    });

    let text = response.text ?? "";
    text = text.replace(/^```json\s*/i, "").replace(/```\s*$/, "").trim();
    return JSON.parse(text);
  }

  private replaceQuestions(body: string, newQuestions: string[]): string {
    const lines = body.split("\n");
    const result: string[] = [];
    let inQuestions = false;

    for (const line of lines) {
      if (line.includes("## Questions to Complete This Flow")) {
        inQuestions = true;
        result.push(line);
        newQuestions.forEach((q, i) => {
          result.push(`- Q${i + 1}: ${q}`);
        });
        continue;
      }
      if (inQuestions) {
        if (line.startsWith("##")) {
          inQuestions = false;
          result.push(line);
        }
        // skip old question lines
        continue;
      }
      result.push(line);
    }

    return result.join("\n");
  }

  async generateAutomation(
    flowId: string,
    format: string
  ): Promise<{ filePath: string; content: string; format: string; usage: string }> {
    const flow = await this.store.getFlowById(flowId);
    if (!flow) throw new Error(`Flow not found: ${flowId}`);
    if (flow.frontmatter.type !== "complete-flow") {
      throw new Error("Can only generate automations from complete flows");
    }

    const formatInstructions: Record<string, { ext: string; instruction: string }> = {
      python: {
        ext: "py",
        instruction: "Generate a Python script that automates the GOAL of this workflow. Prefer the standard library (pathlib, shutil, urllib.request, subprocess, smtplib, json, re, csv, sqlite3). Use `requests` only if genuinely cleaner than urllib. Use an API SDK when the workflow targets a service that has one (Google APIs, Slack SDK, etc.). Only reach for browser/desktop automation (playwright, selenium, pyautogui, pyperclip) if the goal truly cannot be achieved any other way — and if you do, prefer Playwright over Selenium. Start with a module docstring explaining what the script does and, if UI automation was necessary, why lighter options don't apply.",
      },
      nodejs: {
        ext: "js",
        instruction: "Generate a Node.js script that automates the GOAL of this workflow. Prefer built-in modules (fs, fs/promises, path, child_process, fetch — globally available in modern Node, url, stream, crypto). Use an API SDK when the workflow targets a service with one. Only reach for browser automation (playwright, puppeteer) if the goal truly cannot be achieved any other way — and if you do, prefer Playwright. Start with a top comment block explaining what the script does and, if UI automation was necessary, why lighter options don't apply.",
      },
      "claude-skill": {
        ext: "md",
        instruction: "Generate a Claude Code skill (.md file) that can be used to execute this workflow interactively with a human. The body should describe steps in order with decision points.",
      },
      tutorial: {
        ext: "md",
        instruction: "Generate a step-by-step tutorial document that teaches someone how to perform this workflow manually. Use numbered steps and clear headings.",
      },
    };

    const fmt = formatInstructions[format];
    if (!fmt) {
      throw new Error(`Unknown format: ${format}. Use: python, nodejs, claude-skill, tutorial`);
    }

    const response = await this.genai.models.generateContent({
      model: await this.getAutomationModel(),
      contents: [
        {
          role: "user",
          parts: [
            { text: AUTOMATION_PROMPT },
            { text: `\n\n## Format\n${fmt.instruction}` },
            { text: `\n\n## Flow Document\n${flow.body}` },
          ],
        },
      ],
    });

    let content = (response.text ?? "").trim();
    // Strip common code-fence wrapping (```python ... ``` or ```markdown ... ```)
    content = content.replace(/^```[a-z-]*\s*/i, "").replace(/```\s*$/i, "").trim();

    // Predict the final path so we can embed it in the usage string, which
    // then gets embedded inside the file for Python/Node.js/Tutorial formats.
    const predictedPath = this.store.predictAutomationPath(
      flow.frontmatter.name,
      format,
      fmt.ext
    );
    const usage = buildUsageInstructions(format, predictedPath, content);

    // Format-specific header prepending (Claude Skill stays clean and ignores `usage`)
    content = prependHeader(
      format,
      flow.frontmatter.name,
      flow.frontmatter.trigger ?? "",
      content,
      usage
    );

    const filePath = await this.store.saveAutomation(
      flow.frontmatter.name,
      content,
      format,
      fmt.ext
    );

    return { filePath, content, format, usage };
  }

  private insertAnswer(flow: FlowDocument, questionIndex: number, answer: string): string {
    const lines = flow.body.split("\n");
    const result: string[] = [];
    let qIdx = 0;
    let inQuestions = false;

    for (const line of lines) {
      if (line.includes("## Questions to Complete This Flow")) {
        inQuestions = true;
      }
      if (inQuestions && line.startsWith("##") && !line.includes("Questions")) {
        inQuestions = false;
      }

      result.push(line);

      if (inQuestions && line.startsWith("- Q") && qIdx === questionIndex) {
        result.push(`  **Answer:** ${answer}`);
      }
      if (inQuestions && line.startsWith("- Q")) {
        qIdx++;
      }
    }

    return result.join("\n");
  }

  private async promoteToComplete(
    flow: FlowDocument,
    bodyWithAnswers: string
  ): Promise<boolean> {
    // Use Gemini to synthesize the partial flow + answers into a complete flow
    const response = await this.genai.models.generateContent({
      model: await this.getAutomationModel(),
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `Convert this partial flow into a complete flow document. Use the answers provided to fill in the gaps. Output ONLY the markdown body (no frontmatter), following this structure:

# Flow Name

## Trigger
...

## Steps
1. Step (use IF/ELSE, FOR EACH where appropriate)

## Decision Logic
- condition: how user decides

## Tools & Data Sources
- App: read/write/both

## Automation Classification
- Deterministic steps: list
- AI-required steps: list + why
- Human-approval-required: list + why

## Variations Observed
- variation`,
            },
            { text: `\n\n## Partial Flow with Answers\n${bodyWithAnswers}` },
          ],
        },
      ],
    });

    const completeBody = response.text ?? bodyWithAnswers;

    // Save as complete flow
    const newFrontmatter = {
      ...flow.frontmatter,
      type: "complete-flow" as const,
      confidence: "medium" as const,
    };
    delete (newFrontmatter as Record<string, unknown>).gaps;

    await this.store.promotePartialToComplete(flow.filePath, newFrontmatter, completeBody);

    return true;
  }
}
