import { GoogleGenAI } from "@google/genai";
import { FlowStore } from "./flow-store";
import { loadConfig } from "../config";
import { getEffectiveSettings } from "../ai/mode-presets";
import type { InterviewQuestion, FlowDocument } from "../types";

// Common Python stdlib / Node builtins — anything else is treated as a third-party dep
const PYTHON_STDLIB = new Set([
  "os", "sys", "re", "json", "time", "datetime", "pathlib", "subprocess", "shutil",
  "random", "math", "collections", "itertools", "functools", "typing", "logging",
  "argparse", "io", "tempfile", "glob", "csv", "sqlite3", "urllib", "http", "email",
  "base64", "hashlib", "hmac", "uuid", "threading", "multiprocessing", "asyncio",
  "concurrent", "queue", "socket", "ssl", "xml", "html", "string", "textwrap", "traceback",
]);
const NODE_BUILTINS = new Set([
  "fs", "path", "os", "crypto", "http", "https", "url", "querystring", "stream",
  "util", "events", "child_process", "readline", "assert", "buffer", "process",
  "timers", "zlib", "dns", "net", "tls", "v8", "worker_threads",
]);

function prependHeader(
  format: string,
  flowName: string,
  trigger: string,
  content: string,
  usageMarkdown: string
): string {
  const now = new Date().toISOString();
  switch (format) {
    case "python": {
      // Strip an existing model-written docstring and replace with ours so the
      // usage block is always present and consistent.
      const stripped = content.replace(/^(?:"""[\s\S]*?"""|'''[\s\S]*?''')\s*/m, "");
      const usageAsComment = usageMarkdown
        .split("\n")
        .map((l) => (l ? `# ${l}` : "#"))
        .join("\n");
      return `"""\n${flowName}\n\nGenerated by FlowMind on ${now}.\nTrigger: ${trigger}\n"""\n\n${usageAsComment}\n\n${stripped}`;
    }
    case "nodejs": {
      const stripped = content.replace(/^\/\*[\s\S]*?\*\/\s*/m, "");
      const usageAsComment = usageMarkdown
        .split("\n")
        .map((l) => (l ? ` * ${l}` : " *"))
        .join("\n");
      return `/**\n * ${flowName}\n *\n * Generated by FlowMind on ${now}.\n * Trigger: ${trigger}\n *\n${usageAsComment}\n */\n\n${stripped}`;
    }
    case "claude-skill": {
      // Claude skill files must stay clean — only frontmatter and body.
      // If the model didn't write frontmatter, add a minimal one; otherwise trust it.
      if (content.startsWith("---")) return content;
      const skillName = flowName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
      return `---\nname: ${skillName}\ndescription: ${trigger || flowName}\n---\n\n${content}`;
    }
    case "tutorial": {
      return `# ${flowName} — Tutorial\n\n> This document is a step-by-step tutorial generated by FlowMind from an observed workflow. It describes how to perform the task manually. No installation or tools required — just follow the steps in order.\n>\n> Generated: ${now}\n\n## How to use this file\n\n${usageMarkdown}\n\n---\n\n${content}`;
    }
    default:
      return content;
  }
}

function buildUsageInstructions(format: string, filePath: string, content: string): string {
  switch (format) {
    case "python": {
      const imports = detectPythonImports(content);
      const external = imports.filter((i) => !PYTHON_STDLIB.has(i));
      const lines = [
        `**How to run this script**`,
        "",
        "```bash",
        `python "${filePath}"`,
        "```",
      ];
      if (external.length > 0) {
        lines.push("", `This script imports non-stdlib packages. Install them first:`, "", "```bash", `pip install ${external.join(" ")}`, "```");
      }
      return lines.join("\n");
    }
    case "nodejs": {
      const imports = detectNodeImports(content);
      const external = imports.filter((i) => !NODE_BUILTINS.has(i) && !i.startsWith("."));
      const lines = [
        `**How to run this script**`,
        "",
        "```bash",
        `node "${filePath}"`,
        "```",
      ];
      if (external.length > 0) {
        lines.push("", `This script imports non-builtin packages. Install them first:`, "", "```bash", `npm install ${external.join(" ")}`, "```");
      }
      return lines.join("\n");
    }
    case "claude-skill": {
      return [
        `**How to use this as a Claude Code skill**`,
        "",
        `1. Copy this file into the \`.claude/skills/\` folder of any project where you want to use it`,
        `2. The skill will be auto-discovered by Claude Code next time you open that project`,
        `3. Invoke it by typing \`/<skill-name>\` in the Claude Code chat`,
      ].join("\n");
    }
    case "tutorial": {
      return [
        `**How to use this tutorial**`,
        "",
        `This is a plain markdown document. Open it in any markdown viewer or text editor and follow the steps in order. Nothing to install, nothing to run.`,
      ].join("\n");
    }
    default:
      return "";
  }
}

function detectPythonImports(content: string): string[] {
  const imports = new Set<string>();
  for (const line of content.split("\n")) {
    const m1 = line.match(/^\s*import\s+([a-zA-Z_][\w.]*)/);
    const m2 = line.match(/^\s*from\s+([a-zA-Z_][\w.]*)\s+import/);
    const name = (m1?.[1] ?? m2?.[1] ?? "").split(".")[0];
    if (name) imports.add(name);
  }
  return Array.from(imports);
}

function detectNodeImports(content: string): string[] {
  const imports = new Set<string>();
  const patterns = [
    /require\(['"]([^'"]+)['"]\)/g,
    /import\s+.*?\s+from\s+['"]([^'"]+)['"]/g,
    /import\s+['"]([^'"]+)['"]/g,
  ];
  for (const pattern of patterns) {
    let m;
    while ((m = pattern.exec(content)) !== null) {
      const raw = m[1];
      if (!raw.startsWith(".")) {
        // Strip scoped package path (e.g. @scope/pkg/sub → @scope/pkg)
        const parts = raw.split("/");
        imports.add(raw.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0]);
      }
    }
  }
  return Array.from(imports);
}

const AUTOMATION_PROMPT = `You are FlowMind, an AI that generates automations from documented workflows.

Given the complete flow document below, generate the requested output format.

RULES:
- The automation must faithfully implement ALL steps in the flow
- Include error handling for external service calls
- Add comments explaining decision logic
- Never hardcode sensitive values — use environment variables
- Mark steps that need human approval with clear prompts

Respond with ONLY the requested code/document, no explanations.`;

export class InterviewEngine {
  private store: FlowStore;
  private genai: GoogleGenAI;

  constructor(store: FlowStore) {
    this.store = store;

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    this.genai = new GoogleGenAI({ apiKey });
  }

  private async getAutomationModel(): Promise<string> {
    const config = await loadConfig();
    return getEffectiveSettings(config).automationModel;
  }

  async getQuestions(flowId: string): Promise<InterviewQuestion[]> {
    const flow = await this.store.getFlowById(flowId);
    if (!flow) throw new Error(`Flow not found: ${flowId}`);
    if (flow.frontmatter.type !== "partial-flow") {
      return []; // complete flows have no questions
    }

    const questions: InterviewQuestion[] = [];
    const lines = flow.body.split("\n");
    let inQuestions = false;
    let index = 0;

    for (const line of lines) {
      if (line.includes("## Questions to Complete This Flow")) {
        inQuestions = true;
        continue;
      }
      if (inQuestions && line.startsWith("##")) break;
      if (inQuestions && line.startsWith("- Q")) {
        const questionText = line.replace(/^- Q\d+:\s*/, "").trim();
        questions.push({
          index,
          question: questionText,
          answered: false,
        });
        index++;
      }
    }

    return questions;
  }

  async submitAllAnswers(
    flowId: string,
    answers: Record<number, string>
  ): Promise<{ promoted: boolean; newQuestions?: InterviewQuestion[] }> {
    const flow = await this.store.getFlowById(flowId);
    if (!flow) throw new Error(`Flow not found: ${flowId}`);

    const questions = await this.getQuestions(flowId);

    // Insert all answers into the body
    let updatedBody = flow.body;
    for (const q of questions) {
      const answer = answers[q.index];
      if (answer?.trim()) {
        q.answered = true;
        q.answer = answer;
        updatedBody = this.insertAnswer(
          { ...flow, body: updatedBody },
          q.index,
          answer
        );
      }
    }

    // Ask Gemini to evaluate: promote to complete, or generate follow-up questions
    const evalResult = await this.evaluateCompleteness(flow, updatedBody);

    if (evalResult.status === "complete") {
      await this.promoteToComplete(
        { ...flow, body: updatedBody },
        evalResult.body
      );
      return { promoted: true };
    }

    // Still gaps — update the partial flow with answers + new questions
    const newBody = this.replaceQuestions(updatedBody, evalResult.questions);
    const newFrontmatter = {
      ...flow.frontmatter,
      gaps: evalResult.questions.length,
    };
    await this.store.updateFlow(flow.filePath, newFrontmatter, newBody);

    const newQuestions = evalResult.questions.map((q, i) => ({
      index: i,
      question: q,
      answered: false,
    }));

    return { promoted: false, newQuestions };
  }

  private async evaluateCompleteness(
    flow: FlowDocument,
    bodyWithAnswers: string
  ): Promise<
    | { status: "complete"; body: string }
    | { status: "incomplete"; questions: string[] }
  > {
    const response = await this.genai.models.generateContent({
      model: await this.getAutomationModel(),
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `You are FlowMind. A user answered interview questions about a partial workflow. Evaluate whether the flow is now complete enough to document, or if there are still gaps.

Respond with ONLY valid JSON in one of these formats:

If the flow is complete (all steps are clear and reproducible):
{
  "status": "complete",
  "body": "Full markdown flow document (# Name, ## Trigger, ## Steps, ## Decision Logic, ## Tools & Data Sources, ## Automation Classification, ## Variations Observed)"
}

If there are still gaps that need clarification:
{
  "status": "incomplete",
  "questions": ["Q1: specific follow-up question", "Q2: ..."]
}

Rules:
- A flow is complete when ALL steps are clear, specific, and reproducible by someone else
- If the user's answers introduced new ambiguity or referenced unknown steps, ask about those
- Keep follow-up questions specific and actionable
- Do NOT ask more than 3 follow-up questions at a time`,
            },
            {
              text: `\n\n## Partial Flow with Answers\n${bodyWithAnswers}`,
            },
          ],
        },
      ],
      config: { responseMimeType: "application/json" },
    });

    let text = response.text ?? "";
    text = text.replace(/^```json\s*/i, "").replace(/```\s*$/, "").trim();
    return JSON.parse(text);
  }

  private replaceQuestions(body: string, newQuestions: string[]): string {
    const lines = body.split("\n");
    const result: string[] = [];
    let inQuestions = false;

    for (const line of lines) {
      if (line.includes("## Questions to Complete This Flow")) {
        inQuestions = true;
        result.push(line);
        newQuestions.forEach((q, i) => {
          result.push(`- Q${i + 1}: ${q}`);
        });
        continue;
      }
      if (inQuestions) {
        if (line.startsWith("##")) {
          inQuestions = false;
          result.push(line);
        }
        // skip old question lines
        continue;
      }
      result.push(line);
    }

    return result.join("\n");
  }

  async generateAutomation(
    flowId: string,
    format: string
  ): Promise<{ filePath: string; content: string; format: string; usage: string }> {
    const flow = await this.store.getFlowById(flowId);
    if (!flow) throw new Error(`Flow not found: ${flowId}`);
    if (flow.frontmatter.type !== "complete-flow") {
      throw new Error("Can only generate automations from complete flows");
    }

    const formatInstructions: Record<string, { ext: string; instruction: string }> = {
      python: {
        ext: "py",
        instruction: "Generate a Python script that automates this workflow. Use standard libraries where possible, subprocess for CLI tools, and requests for HTTP calls. Start the script with a module docstring describing what it does.",
      },
      nodejs: {
        ext: "js",
        instruction: "Generate a Node.js script that automates this workflow. Use built-in modules and fetch for HTTP calls. Start the script with a top comment block describing what it does.",
      },
      "claude-skill": {
        ext: "md",
        instruction: "Generate a Claude Code skill (.md file) that can be used to execute this workflow interactively with a human. The body should describe steps in order with decision points.",
      },
      tutorial: {
        ext: "md",
        instruction: "Generate a step-by-step tutorial document that teaches someone how to perform this workflow manually. Use numbered steps and clear headings.",
      },
    };

    const fmt = formatInstructions[format];
    if (!fmt) {
      throw new Error(`Unknown format: ${format}. Use: python, nodejs, claude-skill, tutorial`);
    }

    const response = await this.genai.models.generateContent({
      model: await this.getAutomationModel(),
      contents: [
        {
          role: "user",
          parts: [
            { text: AUTOMATION_PROMPT },
            { text: `\n\n## Format\n${fmt.instruction}` },
            { text: `\n\n## Flow Document\n${flow.body}` },
          ],
        },
      ],
    });

    let content = (response.text ?? "").trim();
    // Strip common code-fence wrapping (```python ... ``` or ```markdown ... ```)
    content = content.replace(/^```[a-z-]*\s*/i, "").replace(/```\s*$/i, "").trim();

    // Predict the final path so we can embed it in the usage string, which
    // then gets embedded inside the file for Python/Node.js/Tutorial formats.
    const predictedPath = this.store.predictAutomationPath(
      flow.frontmatter.name,
      format,
      fmt.ext
    );
    const usage = buildUsageInstructions(format, predictedPath, content);

    // Format-specific header prepending (Claude Skill stays clean and ignores `usage`)
    content = prependHeader(
      format,
      flow.frontmatter.name,
      flow.frontmatter.trigger ?? "",
      content,
      usage
    );

    const filePath = await this.store.saveAutomation(
      flow.frontmatter.name,
      content,
      format,
      fmt.ext
    );

    return { filePath, content, format, usage };
  }

  private insertAnswer(flow: FlowDocument, questionIndex: number, answer: string): string {
    const lines = flow.body.split("\n");
    const result: string[] = [];
    let qIdx = 0;
    let inQuestions = false;

    for (const line of lines) {
      if (line.includes("## Questions to Complete This Flow")) {
        inQuestions = true;
      }
      if (inQuestions && line.startsWith("##") && !line.includes("Questions")) {
        inQuestions = false;
      }

      result.push(line);

      if (inQuestions && line.startsWith("- Q") && qIdx === questionIndex) {
        result.push(`  **Answer:** ${answer}`);
      }
      if (inQuestions && line.startsWith("- Q")) {
        qIdx++;
      }
    }

    return result.join("\n");
  }

  private async promoteToComplete(
    flow: FlowDocument,
    bodyWithAnswers: string
  ): Promise<boolean> {
    // Use Gemini to synthesize the partial flow + answers into a complete flow
    const response = await this.genai.models.generateContent({
      model: await this.getAutomationModel(),
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `Convert this partial flow into a complete flow document. Use the answers provided to fill in the gaps. Output ONLY the markdown body (no frontmatter), following this structure:

# Flow Name

## Trigger
...

## Steps
1. Step (use IF/ELSE, FOR EACH where appropriate)

## Decision Logic
- condition: how user decides

## Tools & Data Sources
- App: read/write/both

## Automation Classification
- Deterministic steps: list
- AI-required steps: list + why
- Human-approval-required: list + why

## Variations Observed
- variation`,
            },
            { text: `\n\n## Partial Flow with Answers\n${bodyWithAnswers}` },
          ],
        },
      ],
    });

    const completeBody = response.text ?? bodyWithAnswers;

    // Save as complete flow
    const newFrontmatter = {
      ...flow.frontmatter,
      type: "complete-flow" as const,
      confidence: "medium" as const,
    };
    delete (newFrontmatter as Record<string, unknown>).gaps;

    await this.store.saveFlow("complete", newFrontmatter, completeBody);
    // Remove the partial flow file
    const fsp = await import("node:fs/promises");
    await fsp.unlink(flow.filePath).catch(() => {});

    return true;
  }
}
