import { GoogleGenAI } from "@google/genai";
import type { FlowParameter } from "../types";

/**
 * Diagnose a failed automation script and produce a patched version.
 *
 * Called when a python/nodejs automation exits non-zero. The doctor gets
 * the script source, the captured stdout/stderr, the exit code, the flow's
 * body (goal + observed steps) and the parameter values the user supplied.
 * It returns a full replacement script that is supposed to reach the same
 * goal while avoiding whatever caused the previous failure.
 *
 * The doctor is single-shot: one Gemini call, no tools. It is NOT supposed
 * to guarantee a fix — callers should keep the original script intact and
 * write the patched version as a new versioned file (e.g. `script.v2.py`),
 * so a bad patch is recoverable without user data loss.
 */

const DOCTOR_PROMPT = `You are FlowMind's ScriptDoctor. A generated automation script failed when the user tried to run it. Your job is to analyse the error and produce a patched version of the script that reaches the same goal.

STRICT RULES — READ ALL OF THEM:

1. Return ONLY the full replacement script source. No explanations, no commentary, no code fences. Whatever you return will be written to disk verbatim and executed.

2. Preserve the docstring / header comment and any usage instructions at the top of the script. Do NOT remove the "Generated by FlowMind on ..." block.

3. Preserve EVERY parameter name exactly as it appears in the "Parameters" section. The host runs the script with \`--<name> <value>\` flags AND sets \`FLOWMIND_PARAM_<NAME_UPPER>\` env vars. Renaming a flag will break the form-based runner. If the script used argparse before, keep using argparse; if it parsed process.argv manually, keep that style.

4. Do NOT add interactive prompts (input(), readline, prompt()) for parameter values. Parameters come from the CLI flags / env vars already passed in.

5. Fix the ROOT CAUSE of the failure. Typical patterns:
   - \`ENOENT\` / path not found: the path the script hard-coded does not exist on this machine. The most common example is OneDrive-redirected Desktop: \`C:\\Users\\<user>\\Desktop\` is absent, but \`C:\\Users\\<user>\\OneDrive\\Desktop\` exists. On Windows, resolve Desktop/Documents via the \`USERPROFILE\` env var plus candidate subfolders (\`\\Desktop\`, \`\\OneDrive\\Desktop\`) and pick the first that exists. For portable Python use \`pathlib.Path.home() / "OneDrive" / "Desktop"\` or fall back to \`pathlib.Path.home() / "Desktop"\`.
   - \`404\` from a direct URL guess (e.g. \`en.wikipedia.org/wiki/<subject>\`): the assumption that the subject maps to a canonical URL is wrong. Switch to the service's search API, take the first result, then fetch.
   - \`ModuleNotFoundError\` / \`Cannot find module\`: suggest the minimum change that uses the standard library instead, or at least fall back gracefully. Do NOT add pip/npm install commands — package installation is a separate user action. If the module really is needed, still return a script that works (e.g. stdlib \`urllib.request\` instead of \`requests\`).
   - Windows path vs POSIX path mismatches: always use \`pathlib.Path\` / \`path.join\` / \`os.path.join\` rather than hard-coded backslashes.
   - UnicodeDecodeError on subprocess output: use \`encoding="utf-8", errors="replace"\` or decode bytes explicitly.
   - Auth / 401 / 403: read credentials from env vars, and if missing, print a clear "set X env var" message and exit 2 (don't hang).

6. If the error is a genuine hard block (e.g. a required external service is unreachable, or the workflow requires a private API the script has no credentials for), produce a script that prints a clear diagnostic line and exits 2 — don't silently try to reach the same goal via a path that also won't work. Still return a full valid script.

7. The patched script MUST be meaningfully different from the original. If you can't identify what went wrong, still produce a script that at minimum improves error messages and prints a diagnostic for each step, so the next run is easier to debug.

Return the full script now.`;

export interface DoctorInput {
  /** The language the script is written in. */
  format: "python" | "nodejs";
  /** Original script content that just failed. */
  originalScript: string;
  /** stdout captured during the failed run. */
  stdout: string;
  /** stderr captured during the failed run. */
  stderr: string;
  /** Process exit code (null if the process was killed). */
  exitCode: number | null;
  /** Flow body (goal, steps, decision logic). Helps the doctor understand intent. */
  flowBody: string;
  /** Declared parameters for this flow; the patched script MUST still accept all of them. */
  parameters: FlowParameter[];
  /** Param values the user supplied this run (useful context for reproducing the failure). */
  paramValues: Record<string, string>;
}

export interface DoctorResult {
  /** The patched script content, ready to write to disk. */
  patched: string;
  /** Short human-readable summary of what the doctor thought was wrong. Best-effort; optional. */
  diagnosis?: string;
}

export class ScriptDoctor {
  private genai: GoogleGenAI;

  constructor() {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is required");
    }
    this.genai = new GoogleGenAI({ apiKey });
  }

  /**
   * Ask Gemini to produce a patched script. Throws if the response is
   * unusable (empty, identical to original, or missing declared parameter
   * names). Callers should treat a throw as "retry-not-possible" and show
   * the raw error to the user instead of silently re-running something
   * that won't work.
   */
  async fix(input: DoctorInput, model: string): Promise<DoctorResult> {
    const paramsSection = this.buildParamsSection(input.parameters, input.paramValues);
    const truncatedStdout = truncate(input.stdout, 4000);
    const truncatedStderr = truncate(input.stderr, 8000);

    const prompt = [
      DOCTOR_PROMPT,
      "",
      `## Language`,
      input.format,
      "",
      `## Flow intent (what the script is supposed to accomplish)`,
      input.flowBody,
      "",
      paramsSection,
      "",
      `## Exit code`,
      String(input.exitCode ?? "null (killed)"),
      "",
      `## stderr`,
      truncatedStderr || "(empty)",
      "",
      `## stdout`,
      truncatedStdout || "(empty)",
      "",
      `## Failed script (full source)`,
      input.originalScript,
    ].join("\n");

    const apiCall = this.genai.models.generateContent({
      model,
      contents: [{ role: "user", parts: [{ text: prompt }] }],
    });

    const response = await Promise.race([
      apiCall,
      new Promise<never>((_, reject) =>
        setTimeout(() => reject(new Error("ScriptDoctor timed out after 90s")), 90_000)
      ),
    ]);

    let patched = (response.text ?? "").trim();
    // Strip optional code fences the model sometimes adds despite the prompt.
    patched = patched.replace(/^```[a-zA-Z0-9_-]*\s*/m, "").replace(/```\s*$/m, "").trim();

    if (patched.length < 20) {
      throw new Error("ScriptDoctor returned an empty or near-empty patch.");
    }
    if (patched === input.originalScript.trim()) {
      throw new Error("ScriptDoctor returned an unchanged script — no fix applied.");
    }

    // Parameter-name preservation: every declared parameter name must still
    // appear somewhere in the patched source. Otherwise the form-runner will
    // pass flags the script ignores, and we're back at square one.
    const missing: string[] = [];
    for (const p of input.parameters) {
      if (!patched.includes(p.name)) missing.push(p.name);
    }
    if (missing.length > 0) {
      throw new Error(
        `ScriptDoctor dropped declared parameter(s): ${missing.join(", ")}. Patch rejected.`
      );
    }

    return { patched };
  }

  private buildParamsSection(
    parameters: FlowParameter[],
    paramValues: Record<string, string>
  ): string {
    if (parameters.length === 0 && Object.keys(paramValues).length === 0) {
      return "## Parameters\n(none declared)";
    }
    const lines: string[] = ["## Parameters (names MUST be preserved verbatim)"];
    for (const p of parameters) {
      const value = paramValues[p.name];
      const shown = value === undefined ? "(not supplied)" : JSON.stringify(value);
      lines.push(`- --${p.name} — ${p.description} | supplied value: ${shown}`);
    }
    // Any extra supplied params (form-detected ones not in flow metadata) also
    // need to keep their names. Include them so the doctor doesn't rename.
    for (const [name, value] of Object.entries(paramValues)) {
      if (parameters.some((p) => p.name === name)) continue;
      lines.push(`- --${name} — (supplied at runtime, no metadata) | value: ${JSON.stringify(value)}`);
    }
    return lines.join("\n");
  }
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  const head = text.slice(0, Math.floor(max * 0.3));
  const tail = text.slice(-Math.floor(max * 0.7));
  return `${head}\n[... ${text.length - max} chars omitted ...]\n${tail}`;
}
